# Generated by Django 5.1.1 on 2024-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
