# Generated by Django 5.1.1 on 2024-10-02 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=255)),
                (
                    "collection_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("task_end_time", models.TimeField(default=django.utils.timezone.now)),
                ("total_collected_litter", models.FloatField(blank=True, null=True)),
                ("collected_serial_numbers", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
