# Generated by Django 5.1.1 on 2024-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coastline",
            name="alias_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
