# Generated by Django 5.1.1 on 2024-09-27 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coast_name", models.CharField(max_length=255)),
                ("coast_length", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("photo", models.ImageField(upload_to="photos/")),
                ("estimated_litter_amount", models.FloatField()),
                (
                    "main_litter_type",
                    models.IntegerField(
                        choices=[
                            (1, "Fishing Gear"),
                            (2, "Buoys"),
                            (3, "Household Waste"),
                            (4, "Large Illegal Dumping"),
                            (5, "Vegetation"),
                        ]
                    ),
                ),
            ],
        ),
    ]
