# Generated by Django 5.1.1 on 2024-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigation",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photos/"),
        ),
    ]
