# Generated by Django 5.1.1 on 2024-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0002_alter_investigation_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigation",
            name="investigation_serial_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="investigation",
            name="investigator_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="investigation",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
