# Generated by Django 5.1.1 on 2024-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanup",
            name="arrival_photo",
            field=models.ImageField(blank=True, upload_to="photos/arrival/"),
        ),
        migrations.AlterField(
            model_name="cleanup",
            name="completion_photo_coast",
            field=models.ImageField(blank=True, upload_to="photos/completion/coast/"),
        ),
        migrations.AlterField(
            model_name="cleanup",
            name="completion_photo_collection",
            field=models.ImageField(
                blank=True, upload_to="photos/completion/collection/"
            ),
        ),
    ]
