# Generated by Django 5.1.1 on 2024-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanup", "0002_alter_cleanup_arrival_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cleanup",
            old_name="arrival_latitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="cleanup",
            old_name="arrival_longitude",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="cleanup",
            old_name="arrival_timestamp",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="cleanup",
            name="arrival_photo",
        ),
        migrations.RemoveField(
            model_name="cleanup",
            name="completion_photo_coast",
        ),
        migrations.RemoveField(
            model_name="cleanup",
            name="completion_photo_collection",
        ),
        migrations.AddField(
            model_name="cleanup",
            name="calculated_litter_amount",
            field=models.FloatField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cleanup",
            name="cleaner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cleanup",
            name="cleanup_serial_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="cleanup",
            name="collection_photo",
            field=models.ImageField(blank=True, upload_to="photos/collection/"),
        ),
        migrations.AddField(
            model_name="cleanup",
            name="completion_photo_collection_site",
            field=models.ImageField(blank=True, upload_to="photos/completion/site/"),
        ),
        migrations.AddField(
            model_name="cleanup",
            name="completion_photo_landscape",
            field=models.ImageField(
                blank=True, upload_to="photos/completion/landscape/"
            ),
        ),
    ]
