# Generated by Django 5.1.1 on 2024-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanup", "0003_rename_arrival_latitude_cleanup_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanup",
            name="collection_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/collection/"
            ),
        ),
        migrations.AlterField(
            model_name="cleanup",
            name="completion_photo_collection_site",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/completion/site/"
            ),
        ),
        migrations.AlterField(
            model_name="cleanup",
            name="completion_photo_landscape",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/completion/landscape/"
            ),
        ),
    ]
