# Generated by Django 5.1.1 on 2024-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanup", "0004_alter_cleanup_collection_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleanup",
            name="is_collected",
            field=models.BooleanField(default=False),
        ),
    ]
